spring.application.name=finance-tracker
spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=postgres
spring.datasource.password=149181
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=djkei0928cnfk39cthdn92109vn9823hHOA91298cJUWSI
jwt.expiration=86400000